"""Regenerate minimax certificates; SciPy is a developer-only dependency.

First run test_postflop_convergence --export-matrix <matrix.txt>. The executable
enumerates final boards and all 16 x 16 pure-policy matchups independently of
the production CFR traversal and best-response evaluator.
"""

import argparse
from pathlib import Path

import numpy as np
from scipy.optimize import linprog


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("matrix", type=Path)
    parser.add_argument("header", type=Path)
    args = parser.parse_args()
    values = iter(args.matrix.read_text().split())
    certificates = []
    for _ in range(2):
        street = int(next(values))
        matrix = np.array([float(next(values)) for _ in range(256)]).reshape(16, 16)
        objective = np.r_[np.zeros(16), -1.0]
        p0 = linprog(objective, A_ub=np.c_[-matrix.T, np.ones(16)], b_ub=np.zeros(16),
                     A_eq=[np.r_[np.ones(16), 0.0]], b_eq=[1.0],
                     bounds=[(0.0, None)] * 16 + [(None, None)], method="highs")
        p1 = linprog(-objective, A_ub=np.c_[matrix, -np.ones(16)], b_ub=np.zeros(16),
                     A_eq=[np.r_[np.ones(16), 0.0]], b_eq=[1.0],
                     bounds=[(0.0, None)] * 16 + [(None, None)], method="highs")
        assert p0.success and p1.success
        assert abs(p0.x[-1] - p1.x[-1]) < 1e-7
        lower = np.min(p0.x[:16] @ matrix)
        upper = np.max(matrix @ p1.x[:16])
        assert upper - lower < 1e-7
        value = (lower + upper) / 2.0
        vector = lambda x: "{" + ", ".join(format(float(v), ".17g") for v in x) + "}"
        certificates.append("    {" + str(street) + ", " + format(value, ".17g") + ", "
                            + vector(p0.x[:16]) + ", " + vector(p1.x[:16]) + "}")
        print(f"{street}-card minimax value={value:.12f}, certified gap={upper - lower:.3g}")
    assert next(values, None) is None
    args.header.write_text(
        "// Generated by tests/generate_postflop_reference.py.\n"
        "// Every pure-policy inequality is rechecked at test runtime.\n"
        "#pragma once\n#include <array>\n"
        "struct PostflopReference {\n    int street;\n    double value;\n"
        "    std::array<double, 16> p0, p1;\n};\n"
        "inline constexpr std::array<PostflopReference, 2> postflop_references = {{\n"
        + ",\n".join(certificates) + "\n}};\n"
    )


if __name__ == "__main__":
    main()
