// Generated by tests/generate_postflop_reference.py.
// Every pure-policy inequality is rechecked at test runtime.
#pragma once
#include <array>
struct PostflopReference {
    int street;
    double value;
    std::array<double, 16> p0, p1;
};
inline constexpr std::array<PostflopReference, 2> postflop_references = {{
    {4, 482.9545454545455, {0, 0.77556818181818166, 0, 0.22443181818181834, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0.66666666666666663, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.33333333333333337, 0, 0, 0}},
    {3, 257.85552523357404, {0, 0.5309568480300193, 0, 0, 0.4690431519699807, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0.57129455909943794, 0, 0, 0, 0, 0, 0, 0, 0.42870544090056206, 0, 0}}
}};
